version: '3.3'
services:
  typebot-db:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  typebot-builder:
    ports:
      - 3001:3000
    image: baptistearno/typebot-builder:2.16
    container_name: typebot-builder
    restart: always
    depends_on:
      - typebot-db
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebot.refactorsistemas.com.br
      - NEXT_PUBLIC_VIEWER_URL=https://chat.refactorsistemas.com.br
      - ENCRYPTION_SECRET=2PVq+hzRRCWKTqHebJyssH3FeMPb9jkm
      - ADMIN_EMAIL=souzadeveloper@gmail.com
      - SMTP_SECURE=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USERNAME=souzadeveloper@gmail.com
      - SMTP_PASSWORD=axqkwxouzpkjiqad
      - NEXT_PUBLIC_SMTP_FROM='Suporte Typebot' <souzadeveloper@gmail.com>
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=Minio@891063
      - S3_BUCKET=typebot
      - S3_ENDPOINT=s3.refactorsistemas.com.br

  typebot-viewer:
    ports:
      - 3002:3000
    image: baptistearno/typebot-viewer:2.16
    container_name: typebot-viewer
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=https://chat.refactorsistemas.com.br
      - ENCRYPTION_SECRET=2PVq+hzRRCWKTqHebJyssH3FeMPb9jkm
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=Minio@891063
      - S3_BUCKET=typebot
      - S3_ENDPOINT=s3.refactorsistemas.com.br

  mail:
    image: bytemark/smtp
    container_name: mail
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9090"
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Minio@891063
    volumes:
      - s3_data:/data
      
  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio Minio@891063;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "

  nginx:
    #image: nginx:latest
    build: 
      context: nginx
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
    - ./nginx/conf:/etc/nginx/conf.d:rw
    - ./certbot_data/conf:/etc/letsencrypt:rw
    - ./certbot_data/www:/var/www/certbot:rw

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
    - ./certbot_data/conf:/etc/letsencrypt:rw
    - ./certbot_data/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"

volumes:
  db_data:
  s3_data:
